// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"fmt"
	"selfregi/ent/cartdetail"
	"selfregi/ent/predicate"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CartDetailDelete is the builder for deleting a CartDetail entity.
type CartDetailDelete struct {
	config
	hooks    []Hook
	mutation *CartDetailMutation
}

// Where appends a list predicates to the CartDetailDelete builder.
func (cdd *CartDetailDelete) Where(ps ...predicate.CartDetail) *CartDetailDelete {
	cdd.mutation.Where(ps...)
	return cdd
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (cdd *CartDetailDelete) Exec(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(cdd.hooks) == 0 {
		affected, err = cdd.sqlExec(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CartDetailMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			cdd.mutation = mutation
			affected, err = cdd.sqlExec(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cdd.hooks) - 1; i >= 0; i-- {
			if cdd.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cdd.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cdd.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// ExecX is like Exec, but panics if an error occurs.
func (cdd *CartDetailDelete) ExecX(ctx context.Context) int {
	n, err := cdd.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (cdd *CartDetailDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := &sqlgraph.DeleteSpec{
		Node: &sqlgraph.NodeSpec{
			Table: cartdetail.Table,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cartdetail.FieldID,
			},
		},
	}
	if ps := cdd.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, cdd.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	return affected, err
}

// CartDetailDeleteOne is the builder for deleting a single CartDetail entity.
type CartDetailDeleteOne struct {
	cdd *CartDetailDelete
}

// Exec executes the deletion query.
func (cddo *CartDetailDeleteOne) Exec(ctx context.Context) error {
	n, err := cddo.cdd.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{cartdetail.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (cddo *CartDetailDeleteOne) ExecX(ctx context.Context) {
	cddo.cdd.ExecX(ctx)
}
