// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"selfregi/ent/cart"
	"selfregi/ent/cartdetail"
	"selfregi/ent/predicate"
	"selfregi/ent/visitor"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// CartUpdate is the builder for updating Cart entities.
type CartUpdate struct {
	config
	hooks    []Hook
	mutation *CartMutation
}

// Where appends a list predicates to the CartUpdate builder.
func (cu *CartUpdate) Where(ps ...predicate.Cart) *CartUpdate {
	cu.mutation.Where(ps...)
	return cu
}

// SetVisitorID sets the "visitor_id" field.
func (cu *CartUpdate) SetVisitorID(i int) *CartUpdate {
	cu.mutation.ResetVisitorID()
	cu.mutation.SetVisitorID(i)
	return cu
}

// SetNillableVisitorID sets the "visitor_id" field if the given value is not nil.
func (cu *CartUpdate) SetNillableVisitorID(i *int) *CartUpdate {
	if i != nil {
		cu.SetVisitorID(*i)
	}
	return cu
}

// AddVisitorID adds i to the "visitor_id" field.
func (cu *CartUpdate) AddVisitorID(i int) *CartUpdate {
	cu.mutation.AddVisitorID(i)
	return cu
}

// ClearVisitorID clears the value of the "visitor_id" field.
func (cu *CartUpdate) ClearVisitorID() *CartUpdate {
	cu.mutation.ClearVisitorID()
	return cu
}

// SetStatus sets the "status" field.
func (cu *CartUpdate) SetStatus(u uint) *CartUpdate {
	cu.mutation.ResetStatus()
	cu.mutation.SetStatus(u)
	return cu
}

// AddStatus adds u to the "status" field.
func (cu *CartUpdate) AddStatus(u int) *CartUpdate {
	cu.mutation.AddStatus(u)
	return cu
}

// SetCreatedAt sets the "created_at" field.
func (cu *CartUpdate) SetCreatedAt(t time.Time) *CartUpdate {
	cu.mutation.SetCreatedAt(t)
	return cu
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cu *CartUpdate) SetNillableCreatedAt(t *time.Time) *CartUpdate {
	if t != nil {
		cu.SetCreatedAt(*t)
	}
	return cu
}

// SetUpdatedAt sets the "updated_at" field.
func (cu *CartUpdate) SetUpdatedAt(t time.Time) *CartUpdate {
	cu.mutation.SetUpdatedAt(t)
	return cu
}

// SetDeletedAt sets the "deleted_at" field.
func (cu *CartUpdate) SetDeletedAt(t time.Time) *CartUpdate {
	cu.mutation.SetDeletedAt(t)
	return cu
}

// AddCartDetailIDs adds the "cart_details" edge to the CartDetail entity by IDs.
func (cu *CartUpdate) AddCartDetailIDs(ids ...int) *CartUpdate {
	cu.mutation.AddCartDetailIDs(ids...)
	return cu
}

// AddCartDetails adds the "cart_details" edges to the CartDetail entity.
func (cu *CartUpdate) AddCartDetails(c ...*CartDetail) *CartUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.AddCartDetailIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the Visitor entity by ID.
func (cu *CartUpdate) SetOwnerID(id int) *CartUpdate {
	cu.mutation.SetOwnerID(id)
	return cu
}

// SetOwner sets the "owner" edge to the Visitor entity.
func (cu *CartUpdate) SetOwner(v *Visitor) *CartUpdate {
	return cu.SetOwnerID(v.ID)
}

// Mutation returns the CartMutation object of the builder.
func (cu *CartUpdate) Mutation() *CartMutation {
	return cu.mutation
}

// ClearCartDetails clears all "cart_details" edges to the CartDetail entity.
func (cu *CartUpdate) ClearCartDetails() *CartUpdate {
	cu.mutation.ClearCartDetails()
	return cu
}

// RemoveCartDetailIDs removes the "cart_details" edge to CartDetail entities by IDs.
func (cu *CartUpdate) RemoveCartDetailIDs(ids ...int) *CartUpdate {
	cu.mutation.RemoveCartDetailIDs(ids...)
	return cu
}

// RemoveCartDetails removes "cart_details" edges to CartDetail entities.
func (cu *CartUpdate) RemoveCartDetails(c ...*CartDetail) *CartUpdate {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cu.RemoveCartDetailIDs(ids...)
}

// ClearOwner clears the "owner" edge to the Visitor entity.
func (cu *CartUpdate) ClearOwner() *CartUpdate {
	cu.mutation.ClearOwner()
	return cu
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (cu *CartUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	cu.defaults()
	if len(cu.hooks) == 0 {
		if err = cu.check(); err != nil {
			return 0, err
		}
		affected, err = cu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CartMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cu.check(); err != nil {
				return 0, err
			}
			cu.mutation = mutation
			affected, err = cu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(cu.hooks) - 1; i >= 0; i-- {
			if cu.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, cu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (cu *CartUpdate) SaveX(ctx context.Context) int {
	affected, err := cu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (cu *CartUpdate) Exec(ctx context.Context) error {
	_, err := cu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cu *CartUpdate) ExecX(ctx context.Context) {
	if err := cu.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cu *CartUpdate) defaults() {
	if _, ok := cu.mutation.UpdatedAt(); !ok {
		v := cart.UpdateDefaultUpdatedAt()
		cu.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cu *CartUpdate) check() error {
	if v, ok := cu.mutation.VisitorID(); ok {
		if err := cart.VisitorIDValidator(v); err != nil {
			return &ValidationError{Name: "visitor_id", err: fmt.Errorf(`ent: validator failed for field "Cart.visitor_id": %w`, err)}
		}
	}
	if _, ok := cu.mutation.OwnerID(); cu.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Cart.owner"`)
	}
	return nil
}

func (cu *CartUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cart.Table,
			Columns: cart.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cart.FieldID,
			},
		},
	}
	if ps := cu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cu.mutation.VisitorID(); ok {
		_spec.SetField(cart.FieldVisitorID, field.TypeInt, value)
	}
	if value, ok := cu.mutation.AddedVisitorID(); ok {
		_spec.AddField(cart.FieldVisitorID, field.TypeInt, value)
	}
	if cu.mutation.VisitorIDCleared() {
		_spec.ClearField(cart.FieldVisitorID, field.TypeInt)
	}
	if value, ok := cu.mutation.Status(); ok {
		_spec.SetField(cart.FieldStatus, field.TypeUint, value)
	}
	if value, ok := cu.mutation.AddedStatus(); ok {
		_spec.AddField(cart.FieldStatus, field.TypeUint, value)
	}
	if value, ok := cu.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cu.mutation.DeletedAt(); ok {
		_spec.SetField(cart.FieldDeletedAt, field.TypeTime, value)
	}
	if cu.mutation.CartDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartDetailsTable,
			Columns: []string{cart.CartDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: cartdetail.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.RemovedCartDetailsIDs(); len(nodes) > 0 && !cu.mutation.CartDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartDetailsTable,
			Columns: []string{cart.CartDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: cartdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.CartDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartDetailsTable,
			Columns: []string{cart.CartDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: cartdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cu.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.OwnerTable,
			Columns: []string{cart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: visitor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cu.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.OwnerTable,
			Columns: []string{cart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: visitor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, cu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// CartUpdateOne is the builder for updating a single Cart entity.
type CartUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *CartMutation
}

// SetVisitorID sets the "visitor_id" field.
func (cuo *CartUpdateOne) SetVisitorID(i int) *CartUpdateOne {
	cuo.mutation.ResetVisitorID()
	cuo.mutation.SetVisitorID(i)
	return cuo
}

// SetNillableVisitorID sets the "visitor_id" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableVisitorID(i *int) *CartUpdateOne {
	if i != nil {
		cuo.SetVisitorID(*i)
	}
	return cuo
}

// AddVisitorID adds i to the "visitor_id" field.
func (cuo *CartUpdateOne) AddVisitorID(i int) *CartUpdateOne {
	cuo.mutation.AddVisitorID(i)
	return cuo
}

// ClearVisitorID clears the value of the "visitor_id" field.
func (cuo *CartUpdateOne) ClearVisitorID() *CartUpdateOne {
	cuo.mutation.ClearVisitorID()
	return cuo
}

// SetStatus sets the "status" field.
func (cuo *CartUpdateOne) SetStatus(u uint) *CartUpdateOne {
	cuo.mutation.ResetStatus()
	cuo.mutation.SetStatus(u)
	return cuo
}

// AddStatus adds u to the "status" field.
func (cuo *CartUpdateOne) AddStatus(u int) *CartUpdateOne {
	cuo.mutation.AddStatus(u)
	return cuo
}

// SetCreatedAt sets the "created_at" field.
func (cuo *CartUpdateOne) SetCreatedAt(t time.Time) *CartUpdateOne {
	cuo.mutation.SetCreatedAt(t)
	return cuo
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (cuo *CartUpdateOne) SetNillableCreatedAt(t *time.Time) *CartUpdateOne {
	if t != nil {
		cuo.SetCreatedAt(*t)
	}
	return cuo
}

// SetUpdatedAt sets the "updated_at" field.
func (cuo *CartUpdateOne) SetUpdatedAt(t time.Time) *CartUpdateOne {
	cuo.mutation.SetUpdatedAt(t)
	return cuo
}

// SetDeletedAt sets the "deleted_at" field.
func (cuo *CartUpdateOne) SetDeletedAt(t time.Time) *CartUpdateOne {
	cuo.mutation.SetDeletedAt(t)
	return cuo
}

// AddCartDetailIDs adds the "cart_details" edge to the CartDetail entity by IDs.
func (cuo *CartUpdateOne) AddCartDetailIDs(ids ...int) *CartUpdateOne {
	cuo.mutation.AddCartDetailIDs(ids...)
	return cuo
}

// AddCartDetails adds the "cart_details" edges to the CartDetail entity.
func (cuo *CartUpdateOne) AddCartDetails(c ...*CartDetail) *CartUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.AddCartDetailIDs(ids...)
}

// SetOwnerID sets the "owner" edge to the Visitor entity by ID.
func (cuo *CartUpdateOne) SetOwnerID(id int) *CartUpdateOne {
	cuo.mutation.SetOwnerID(id)
	return cuo
}

// SetOwner sets the "owner" edge to the Visitor entity.
func (cuo *CartUpdateOne) SetOwner(v *Visitor) *CartUpdateOne {
	return cuo.SetOwnerID(v.ID)
}

// Mutation returns the CartMutation object of the builder.
func (cuo *CartUpdateOne) Mutation() *CartMutation {
	return cuo.mutation
}

// ClearCartDetails clears all "cart_details" edges to the CartDetail entity.
func (cuo *CartUpdateOne) ClearCartDetails() *CartUpdateOne {
	cuo.mutation.ClearCartDetails()
	return cuo
}

// RemoveCartDetailIDs removes the "cart_details" edge to CartDetail entities by IDs.
func (cuo *CartUpdateOne) RemoveCartDetailIDs(ids ...int) *CartUpdateOne {
	cuo.mutation.RemoveCartDetailIDs(ids...)
	return cuo
}

// RemoveCartDetails removes "cart_details" edges to CartDetail entities.
func (cuo *CartUpdateOne) RemoveCartDetails(c ...*CartDetail) *CartUpdateOne {
	ids := make([]int, len(c))
	for i := range c {
		ids[i] = c[i].ID
	}
	return cuo.RemoveCartDetailIDs(ids...)
}

// ClearOwner clears the "owner" edge to the Visitor entity.
func (cuo *CartUpdateOne) ClearOwner() *CartUpdateOne {
	cuo.mutation.ClearOwner()
	return cuo
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (cuo *CartUpdateOne) Select(field string, fields ...string) *CartUpdateOne {
	cuo.fields = append([]string{field}, fields...)
	return cuo
}

// Save executes the query and returns the updated Cart entity.
func (cuo *CartUpdateOne) Save(ctx context.Context) (*Cart, error) {
	var (
		err  error
		node *Cart
	)
	cuo.defaults()
	if len(cuo.hooks) == 0 {
		if err = cuo.check(); err != nil {
			return nil, err
		}
		node, err = cuo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*CartMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = cuo.check(); err != nil {
				return nil, err
			}
			cuo.mutation = mutation
			node, err = cuo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(cuo.hooks) - 1; i >= 0; i-- {
			if cuo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = cuo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, cuo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Cart)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from CartMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (cuo *CartUpdateOne) SaveX(ctx context.Context) *Cart {
	node, err := cuo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (cuo *CartUpdateOne) Exec(ctx context.Context) error {
	_, err := cuo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (cuo *CartUpdateOne) ExecX(ctx context.Context) {
	if err := cuo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (cuo *CartUpdateOne) defaults() {
	if _, ok := cuo.mutation.UpdatedAt(); !ok {
		v := cart.UpdateDefaultUpdatedAt()
		cuo.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (cuo *CartUpdateOne) check() error {
	if v, ok := cuo.mutation.VisitorID(); ok {
		if err := cart.VisitorIDValidator(v); err != nil {
			return &ValidationError{Name: "visitor_id", err: fmt.Errorf(`ent: validator failed for field "Cart.visitor_id": %w`, err)}
		}
	}
	if _, ok := cuo.mutation.OwnerID(); cuo.mutation.OwnerCleared() && !ok {
		return errors.New(`ent: clearing a required unique edge "Cart.owner"`)
	}
	return nil
}

func (cuo *CartUpdateOne) sqlSave(ctx context.Context) (_node *Cart, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   cart.Table,
			Columns: cart.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: cart.FieldID,
			},
		},
	}
	id, ok := cuo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Cart.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := cuo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, cart.FieldID)
		for _, f := range fields {
			if !cart.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != cart.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := cuo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := cuo.mutation.VisitorID(); ok {
		_spec.SetField(cart.FieldVisitorID, field.TypeInt, value)
	}
	if value, ok := cuo.mutation.AddedVisitorID(); ok {
		_spec.AddField(cart.FieldVisitorID, field.TypeInt, value)
	}
	if cuo.mutation.VisitorIDCleared() {
		_spec.ClearField(cart.FieldVisitorID, field.TypeInt)
	}
	if value, ok := cuo.mutation.Status(); ok {
		_spec.SetField(cart.FieldStatus, field.TypeUint, value)
	}
	if value, ok := cuo.mutation.AddedStatus(); ok {
		_spec.AddField(cart.FieldStatus, field.TypeUint, value)
	}
	if value, ok := cuo.mutation.CreatedAt(); ok {
		_spec.SetField(cart.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.UpdatedAt(); ok {
		_spec.SetField(cart.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := cuo.mutation.DeletedAt(); ok {
		_spec.SetField(cart.FieldDeletedAt, field.TypeTime, value)
	}
	if cuo.mutation.CartDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartDetailsTable,
			Columns: []string{cart.CartDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: cartdetail.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.RemovedCartDetailsIDs(); len(nodes) > 0 && !cuo.mutation.CartDetailsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartDetailsTable,
			Columns: []string{cart.CartDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: cartdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.CartDetailsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   cart.CartDetailsTable,
			Columns: []string{cart.CartDetailsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: cartdetail.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if cuo.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.OwnerTable,
			Columns: []string{cart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: visitor.FieldID,
				},
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := cuo.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   cart.OwnerTable,
			Columns: []string{cart.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: &sqlgraph.FieldSpec{
					Type:   field.TypeInt,
					Column: visitor.FieldID,
				},
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Cart{config: cuo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, cuo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{cart.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
