// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"selfregi/ent/journals"
	"selfregi/ent/predicate"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
)

// JournalsUpdate is the builder for updating Journals entities.
type JournalsUpdate struct {
	config
	hooks    []Hook
	mutation *JournalsMutation
}

// Where appends a list predicates to the JournalsUpdate builder.
func (ju *JournalsUpdate) Where(ps ...predicate.Journals) *JournalsUpdate {
	ju.mutation.Where(ps...)
	return ju
}

// SetUpdatedAt sets the "updated_at" field.
func (ju *JournalsUpdate) SetUpdatedAt(t time.Time) *JournalsUpdate {
	ju.mutation.SetUpdatedAt(t)
	return ju
}

// SetDeletedAt sets the "deleted_at" field.
func (ju *JournalsUpdate) SetDeletedAt(t time.Time) *JournalsUpdate {
	ju.mutation.SetDeletedAt(t)
	return ju
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (ju *JournalsUpdate) SetNillableDeletedAt(t *time.Time) *JournalsUpdate {
	if t != nil {
		ju.SetDeletedAt(*t)
	}
	return ju
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (ju *JournalsUpdate) ClearDeletedAt() *JournalsUpdate {
	ju.mutation.ClearDeletedAt()
	return ju
}

// Mutation returns the JournalsMutation object of the builder.
func (ju *JournalsUpdate) Mutation() *JournalsMutation {
	return ju.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (ju *JournalsUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	ju.defaults()
	if len(ju.hooks) == 0 {
		affected, err = ju.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*JournalsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			ju.mutation = mutation
			affected, err = ju.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(ju.hooks) - 1; i >= 0; i-- {
			if ju.hooks[i] == nil {
				return 0, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = ju.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, ju.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (ju *JournalsUpdate) SaveX(ctx context.Context) int {
	affected, err := ju.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (ju *JournalsUpdate) Exec(ctx context.Context) error {
	_, err := ju.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (ju *JournalsUpdate) ExecX(ctx context.Context) {
	if err := ju.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (ju *JournalsUpdate) defaults() {
	if _, ok := ju.mutation.UpdatedAt(); !ok {
		v := journals.UpdateDefaultUpdatedAt()
		ju.mutation.SetUpdatedAt(v)
	}
}

func (ju *JournalsUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   journals.Table,
			Columns: journals.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: journals.FieldID,
			},
		},
	}
	if ps := ju.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := ju.mutation.UpdatedAt(); ok {
		_spec.SetField(journals.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := ju.mutation.DeletedAt(); ok {
		_spec.SetField(journals.FieldDeletedAt, field.TypeTime, value)
	}
	if ju.mutation.DeletedAtCleared() {
		_spec.ClearField(journals.FieldDeletedAt, field.TypeTime)
	}
	if n, err = sqlgraph.UpdateNodes(ctx, ju.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journals.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// JournalsUpdateOne is the builder for updating a single Journals entity.
type JournalsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *JournalsMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (juo *JournalsUpdateOne) SetUpdatedAt(t time.Time) *JournalsUpdateOne {
	juo.mutation.SetUpdatedAt(t)
	return juo
}

// SetDeletedAt sets the "deleted_at" field.
func (juo *JournalsUpdateOne) SetDeletedAt(t time.Time) *JournalsUpdateOne {
	juo.mutation.SetDeletedAt(t)
	return juo
}

// SetNillableDeletedAt sets the "deleted_at" field if the given value is not nil.
func (juo *JournalsUpdateOne) SetNillableDeletedAt(t *time.Time) *JournalsUpdateOne {
	if t != nil {
		juo.SetDeletedAt(*t)
	}
	return juo
}

// ClearDeletedAt clears the value of the "deleted_at" field.
func (juo *JournalsUpdateOne) ClearDeletedAt() *JournalsUpdateOne {
	juo.mutation.ClearDeletedAt()
	return juo
}

// Mutation returns the JournalsMutation object of the builder.
func (juo *JournalsUpdateOne) Mutation() *JournalsMutation {
	return juo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (juo *JournalsUpdateOne) Select(field string, fields ...string) *JournalsUpdateOne {
	juo.fields = append([]string{field}, fields...)
	return juo
}

// Save executes the query and returns the updated Journals entity.
func (juo *JournalsUpdateOne) Save(ctx context.Context) (*Journals, error) {
	var (
		err  error
		node *Journals
	)
	juo.defaults()
	if len(juo.hooks) == 0 {
		node, err = juo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*JournalsMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			juo.mutation = mutation
			node, err = juo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(juo.hooks) - 1; i >= 0; i-- {
			if juo.hooks[i] == nil {
				return nil, fmt.Errorf("ent: uninitialized hook (forgotten import ent/runtime?)")
			}
			mut = juo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, juo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Journals)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from JournalsMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (juo *JournalsUpdateOne) SaveX(ctx context.Context) *Journals {
	node, err := juo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (juo *JournalsUpdateOne) Exec(ctx context.Context) error {
	_, err := juo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (juo *JournalsUpdateOne) ExecX(ctx context.Context) {
	if err := juo.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (juo *JournalsUpdateOne) defaults() {
	if _, ok := juo.mutation.UpdatedAt(); !ok {
		v := journals.UpdateDefaultUpdatedAt()
		juo.mutation.SetUpdatedAt(v)
	}
}

func (juo *JournalsUpdateOne) sqlSave(ctx context.Context) (_node *Journals, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   journals.Table,
			Columns: journals.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeInt,
				Column: journals.FieldID,
			},
		},
	}
	id, ok := juo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Journals.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := juo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, journals.FieldID)
		for _, f := range fields {
			if !journals.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != journals.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := juo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := juo.mutation.UpdatedAt(); ok {
		_spec.SetField(journals.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := juo.mutation.DeletedAt(); ok {
		_spec.SetField(journals.FieldDeletedAt, field.TypeTime, value)
	}
	if juo.mutation.DeletedAtCleared() {
		_spec.ClearField(journals.FieldDeletedAt, field.TypeTime)
	}
	_node = &Journals{config: juo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, juo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{journals.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
